### ISSUE TITLE
Thank you so much for this

### ISSUE THREAD

**Issue by InAnimaTe** [tgogos/kelsey-hightower-wisdom#1]
You are a God (Not really, Kelsey is, but you're not far off)

Might I suggest some quotes from his KubeCon 2019 [talk ](https://www.youtube.com/watch?v=jiaLsxjBeOQ) in San Diego? Utterly remarkable stuff.

Feel free to close this whenever.

**Comment by tgogos** [comment]
Yeah sure! 

> It's not a race if we' re all on the same team

for example, should definitely be added! :-)

**Comment by InAnimaTe** [comment]
Ok I'll do a PR one day with quotes from that talk. I was sitting in the front row during it and my brain just exploded.

Thanks again!
