### ISSUE TITLE
Rearrange quotes - sort by time

### ISSUE THREAD

**Issue by tgogos** [tgogos/kelsey-hightower-wisdom#6]
Reorder some of the content...

**Comment by amanydv72** [comment]
I would like to work on this. Can you please assign me?

**Comment by tgogos** [comment]
Hey @amanydv72 thanks! I had already started working on this when I saw your message... I opened a new one for the "Crypto" section. You can contribute on this one. Check #7

**Comment by amanydv72** [comment]
Thank you 😊
